// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  笔记: [
    'notes/notes-intro',
    {
      label: 'TypeScript',
      type: 'category',
      items: ['notes/TypeScript/ts-for-js-devs']    
    },
    {
      label: 'JavaScript',
      type: 'category',
      items: ['notes/Javascript/call-apply-bind'],
    },
    {
      label: '网络安全',
      type: 'category',
      items: ['notes/whitehat/arpspoof', 'notes/whitehat/mdk4']
    },
    {
      label: '资源',
      type: 'category',
      items: ['notes/resources/website'],
      collapsed: false
    }
  ],
  乐趣: [
    'hackfun/hackfun-intro',
    {
      label: 'ArchLinux',
      type: 'category',
      items: ['hackfun/arch/grub', 'hackfun/arch/timesetting', 'hackfun/arch/rtl8812bu', 'hackfun/arch/fancontrol'],
      collapsed: false
    },
    {
      label: 'Openwrt',
      type: 'category',
      items: [
        'hackfun/openwrt/installation',
        'hackfun/openwrt/turboacc',
        'hackfun/openwrt/thirdparty'
      ],
      collapsed: false
    },
    {
      label: '科学上网',
      type: 'category',
      items: [
        'hackfun/net/v2ray-in-campus'
      ],
      collapsed: false
    },
    {
      label: 'Terraria',
      type: 'category',
      items: ['hackfun/terraria/terrariahouses'],
      collapsed: false
    }
  ]
};

module.exports = sidebars;
